### ISSUE TITLE
review

### ISSUE THREAD

**Issue by Zwillinge** [AlenaMikalaeynaLisava/webix#1]
## how to make the app fullscreen

- remove minHeight from datatable
- add `autoheight:false` to form. it is `true` by default, so the form calculates its height as sum of input height.
- remove spacer `{}` from the rows list 

## icon button

instead of combining button and label for "User Profile" button, it's better to use `view:"button", type:"icon"`

## dark toolbar 

instead of describing `webix_dark` class for layout, it's better to use `view:"toolbar", css:"webix_dark"`. this class is built-in

**Comment by Zwillinge** [comment]
##Icon button

- instead of combining button and label for "User Profile" button, it's better to use `view:"button", type:"icon"`

**Comment by AlenaMikalaeynaLisava** [comment]
Thank you. Everything is implemented
